### ISSUE TITLE
Can't load large ctag file larger than 50MB. Loading has been cancelled

### ISSUE THREAD

**Issue by wulftone** [otoniel-isidoro/vscode-ruby-ctags#2]
I encounter the error: "Can't load large ctag file larger than 50MB. Loading has been cancelled" when trying to use this extension.  Not sure why... not sure how to debug!

**Comment by otoniel-isidoro** [comment]
What is the size of you .tags file? 
This error can be because of some directories with many not ruby files that is not excluded from tag indexer...

**Comment by guiloyins** [comment]
I'm also experiencing the same issue. The tags file is just 377734b.

**Comment by otoniel-isidoro** [comment]
This is not a issue. The error occurs when the plugin is not configured. Please follow the instructions on [HowTo](https://github.com/otoniel-isidoro/vscode-ruby-ctags#howto) and try again.

**Comment by ypresto** [comment]
It'd be better if it can be run without configuration..!

**Comment by ypresto** [comment]
Working minimum configuration was below:

```json
  "ctags": {
    "fileName": ".tags"
  }
```
