### ISSUE TITLE
Cannot find the symbol : method_name

### ISSUE THREAD

**Issue by kholbekj** [otoniel-isidoro/vscode-ruby-ctags#6]
Hey, I'm trying to configure it to generate ctags for my full bundle. I messed with the options like so:
```
    "ctags": {
        "executePath": "/Users/kasper/.rbenv/shims/ripper-tags",
        "options": "--tag-file=tags --recursive --force --exclude=/assets/ --exclude=.bundle --exclude=.git/ --exclude=coverage/ --exclude=.arcanist-extensions/ --exclude=log/ --exclude=tmp/ --exclude=bin/ $(bundle list --paths)",
        "fileName": "tags"
    }
```
it generates the tags file fine, but then when i try to do a lookup, it correctly finds the source file:
![cursor_and_searches_controller_rb_-_loveos-frontend](https://cloud.githubusercontent.com/assets/2786571/21614364/79833922-d1d9-11e6-98a9-ce8723dc7198.png)

but then when i press enter:

![searches_controller_rb_-_loveos-frontend](https://cloud.githubusercontent.com/assets/2786571/21614380/8e5b9286-d1d9-11e6-971b-6a0fe099cad2.png)

this happens for all methods, including those directly in the project path.

**Comment by otoniel-isidoro** [comment]
let me understand what you are trying to do...
the config for the ripper-tags **executePath** looks ok but in the **options** I think the following command is not valid:  "$(bundle list --paths)" 
If you are trying to make the tags for your entire bundle gems just remove the config "--exclude=.bundle". This just will work if you are using the bundle config to install gems per projects as the following example:

put the following configuration inside the file ~/.bundle/config:

```
BUNDLE_PATH: ".bundle/gems"
BUNDLE_DISABLE_SHARED_GEMS: "true"
```

**Comment by otoniel-isidoro** [comment]
let me know about your environment too because I just tested this extension over a linux environment...

**Comment by kholbekj** [comment]
Gave up on vscode a long time ago, forgot about this.
